### ISSUE TITLE
customVideoInfoWidget isn't defined

### ISSUE THREAD

**Issue by kiloki-official** [quochuynh67/flutter_video_newfeed#4]
Hi, customVideoInfoWidget isn't defined. So your example doesn't work, can you please help? Thanks

**Comment by quochuynh67** [comment]
That my mistake, I uploaded with the old source code. Now I was push new code in 1.0.1. you can check it

<img width="690" alt="image" src="https://user-images.githubusercontent.com/38383168/130363104-d414328e-59a3-4a9a-b7a8-c7a1f03d38c3.png">

**Comment by kiloki-official** [comment]
Fantastic, thanks for your quick response. 

The only thing that is missing, in my opinion, is caching. Would it be possible for you to add this feature?

Thanks

**Comment by kiloki-official** [comment]
Also, FYI, you haven't updated it here: https://pub.dev/packages/flutter_video_newfeed
