### ISSUE TITLE
FlutterError (Unable to load asset: assets/no_result.json)

### ISSUE THREAD

**Issue by herowws** [quochuynh67/flutter_video_newfeed#5]
![image](https://user-images.githubusercontent.com/41428542/148740319-a4b10fce-c087-478a-ab39-9adbe2e90deb.png)

**Comment by lecletest** [comment]
@ximenqing183 please add yourself lottie animation file on your project

**Comment by herowws** [comment]
![image](https://user-images.githubusercontent.com/41428542/148867250-f605c903-cf64-4ea4-9952-ea76037c2229.png)
I can only load 1-6
I can't load 7  8 9 ....

![image](https://user-images.githubusercontent.com/41428542/148867402-8a778cd5-2a2a-4a9a-b2e2-777b160c6ab7.png)
how to use  loadMore()

**Comment by herowws** [comment]
![image](https://user-images.githubusercontent.com/41428542/148867543-98da977c-8925-4ad1-8f70-aefa045e180d.png)

**Comment by herowws** [comment]
help me  give you star

**Comment by herowws** [comment]
![363d37490fa20b6dcdf4946f50cf51cc](https://user-images.githubusercontent.com/41428542/148867996-8a851de8-a71b-4e3a-a6d2-9bcad9e1ce90.gif)

look gif

**Comment by lecletest** [comment]
> ![image](https://user-images.githubusercontent.com/41428542/148867543-98da977c-8925-4ad1-8f70-aefa045e180d.png)

print('loadMore exec') was callled or not
